-- MySQL Script generated by MySQL Workbench
-- Thu Sep  8 19:14:09 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema hpspg12_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema hpspg12_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `hpspg12_db` DEFAULT CHARACTER SET utf8 ;
USE `hpspg12_db` ;

-- -----------------------------------------------------
-- Table `hpspg12_db`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hpspg12_db`.`usuario` (
  `username` VARCHAR(45) NOT NULL,
  `contraseña` VARCHAR(45) NOT NULL,
  `user_type` VARCHAR(45) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `telefono` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`username`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hpspg12_db`.`PersonalSalud`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hpspg12_db`.`PersonalSalud` (
  `persalud_id` INT NOT NULL,
  `persalud_rol` VARCHAR(45) NOT NULL,
  `persalud_especialidad` VARCHAR(45) NOT NULL,
  `persalud_usuario` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`persalud_id`),
  UNIQUE INDEX `personalsalud_id_UNIQUE` (`persalud_id` ASC) VISIBLE,
  INDEX `fk_PersonalSalud_usuario1_idx` (`persalud_usuario` ASC) VISIBLE,
  CONSTRAINT `fk_PersonalSalud_usuario1`
    FOREIGN KEY (`persalud_usuario`)
    REFERENCES `hpspg12_db`.`usuario` (`username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hpspg12_db`.`paciente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hpspg12_db`.`paciente` (
  `pac_id` INT NOT NULL,
  `pac_direc` VARCHAR(45) NOT NULL,
  `pac_ciudad` VARCHAR(45) NOT NULL,
  `pac_datebirth` VARCHAR(45) NOT NULL,
  `pac_personalSalud` INT NOT NULL,
  `pac_usuario` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`pac_id`),
  UNIQUE INDEX `pac_id_UNIQUE` (`pac_id` ASC) VISIBLE,
  INDEX `fk_paciente_PersonalSalud1_idx` (`pac_personalSalud` ASC) VISIBLE,
  INDEX `fk_paciente_usuario1_idx` (`pac_usuario` ASC) VISIBLE,
  CONSTRAINT `fk_paciente_PersonalSalud1`
    FOREIGN KEY (`pac_personalSalud`)
    REFERENCES `hpspg12_db`.`PersonalSalud` (`persalud_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_paciente_usuario1`
    FOREIGN KEY (`pac_usuario`)
    REFERENCES `hpspg12_db`.`usuario` (`username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hpspg12_db`.`familiar`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hpspg12_db`.`familiar` (
  `fam_id` INT NOT NULL,
  `fam_parentesco` VARCHAR(45) NOT NULL,
  `fam_correo` VARCHAR(45) NOT NULL,
  `fam_usuario` VARCHAR(45) NOT NULL,
  `fam_paciente` INT NOT NULL,
  PRIMARY KEY (`fam_id`),
  INDEX `fk_familiar_usuario1_idx` (`fam_usuario` ASC) VISIBLE,
  INDEX `fk_familiar_paciente1_idx` (`fam_paciente` ASC) VISIBLE,
  CONSTRAINT `fk_familiar_usuario1`
    FOREIGN KEY (`fam_usuario`)
    REFERENCES `hpspg12_db`.`usuario` (`username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_familiar_paciente1`
    FOREIGN KEY (`fam_paciente`)
    REFERENCES `hpspg12_db`.`paciente` (`pac_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hpspg12_db`.`signosvitales`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hpspg12_db`.`signosvitales` (
  `sig_id` INT NOT NULL,
  `sig_resp` INT NOT NULL,
  `sig_frec` INT NOT NULL,
  `sig_temp` INT NOT NULL,
  `sig_glicem` INT NOT NULL,
  `sig_pres` VARCHAR(45) NOT NULL,
  `sig_time` VARCHAR(45) NOT NULL,
  `sig_paciente` INT NOT NULL,
  PRIMARY KEY (`sig_id`),
  UNIQUE INDEX `sig_id_UNIQUE` (`sig_id` ASC) VISIBLE,
  INDEX `fk_signosvitales_paciente_idx` (`sig_paciente` ASC) VISIBLE,
  CONSTRAINT `fk_signosvitales_paciente`
    FOREIGN KEY (`sig_paciente`)
    REFERENCES `hpspg12_db`.`paciente` (`pac_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hpspg12_db`.`historiaclinica`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hpspg12_db`.`historiaclinica` (
  `histclin_id` INT NOT NULL,
  `histclin_sugerencia` VARCHAR(45) NOT NULL,
  `histclin_diagnost` VARCHAR(45) NOT NULL,
  `histclin_entorno` VARCHAR(45) NOT NULL,
  `histclin_advicedate` VARCHAR(45) NOT NULL,
  `histclin_descrip` VARCHAR(45) NOT NULL,
  `histclin_paciente` INT NOT NULL,
  PRIMARY KEY (`histclin_id`),
  UNIQUE INDEX `histclin_id_UNIQUE` (`histclin_id` ASC) VISIBLE,
  INDEX `fk_historiaclinica_paciente1_idx` (`histclin_paciente` ASC) VISIBLE,
  CONSTRAINT `fk_historiaclinica_paciente1`
    FOREIGN KEY (`histclin_paciente`)
    REFERENCES `hpspg12_db`.`paciente` (`pac_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
