-- MySQL Script generated by MySQL Workbench
-- Sun Sep  4 19:30:34 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema hospg13_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema hospg13_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `hospg13_db` DEFAULT CHARACTER SET utf8 ;
USE `hospg13_db` ;

-- -----------------------------------------------------
-- Table `hospg13_db`.`medico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospg13_db`.`medico` (
  `med_id` INT NOT NULL,
  `med_nombre` VARCHAR(45) NOT NULL,
  `med_correo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`med_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hospg13_db`.`familiar`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospg13_db`.`familiar` (
  `fam_id` INT NOT NULL,
  `fam_nombre` VARCHAR(45) NOT NULL,
  `fam_correo` VARCHAR(45) NOT NULL,
  `fam_paciente` INT NOT NULL,
  PRIMARY KEY (`fam_id`),
  INDEX `fk_familiar_Paciente_idx` (`fam_paciente` ASC) VISIBLE,
  CONSTRAINT `fk_familiar_Paciente`
    FOREIGN KEY (`fam_paciente`)
    REFERENCES `hospg13_db`.`Paciente` (`pac_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hospg13_db`.`login`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospg13_db`.`login` (
  `log_id` INT NOT NULL,
  `log_usuario` VARCHAR(45) NOT NULL,
  `log_password` VARCHAR(45) NOT NULL,
  `log_medico` INT NOT NULL,
  `log_familiar` INT NOT NULL,
  PRIMARY KEY (`log_id`),
  INDEX `fk_login_medico1_idx` (`log_medico` ASC) VISIBLE,
  INDEX `fk_login_familiar1_idx` (`log_familiar` ASC) VISIBLE,
  CONSTRAINT `fk_login_medico1`
    FOREIGN KEY (`log_medico`)
    REFERENCES `hospg13_db`.`medico` (`med_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_login_familiar1`
    FOREIGN KEY (`log_familiar`)
    REFERENCES `hospg13_db`.`familiar` (`fam_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hospg13_db`.`enfermero`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospg13_db`.`enfermero` (
  `enf_id` INT NOT NULL,
  `enf_nombre` VARCHAR(45) NOT NULL,
  `enf_correo` VARCHAR(45) NOT NULL,
  `enf_login` INT NOT NULL,
  PRIMARY KEY (`enf_id`),
  INDEX `fk_enfermero_login1_idx` (`enf_login` ASC) VISIBLE,
  CONSTRAINT `fk_enfermero_login1`
    FOREIGN KEY (`enf_login`)
    REFERENCES `hospg13_db`.`login` (`log_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hospg13_db`.`Paciente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospg13_db`.`Paciente` (
  `pac_id` INT NOT NULL,
  `pac_nombre` VARCHAR(45) NOT NULL,
  `pac_direccion` VARCHAR(45) NOT NULL,
  `pac_correo` VARCHAR(45) NOT NULL,
  `pac_medico` INT NOT NULL,
  `pac_enfermero` INT NOT NULL,
  `pac_login` INT NOT NULL,
  PRIMARY KEY (`pac_id`),
  INDEX `fk_Paciente_enfermero1_idx` (`pac_enfermero` ASC) VISIBLE,
  INDEX `fk_Paciente_medico1_idx` (`pac_medico` ASC) VISIBLE,
  INDEX `fk_Paciente_login1_idx` (`pac_login` ASC) VISIBLE,
  CONSTRAINT `enfermero`
    FOREIGN KEY (`pac_enfermero`)
    REFERENCES `hospg13_db`.`enfermero` (`enf_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `medico`
    FOREIGN KEY (`pac_medico`)
    REFERENCES `hospg13_db`.`medico` (`med_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `login`
    FOREIGN KEY (`pac_login`)
    REFERENCES `hospg13_db`.`login` (`log_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hospg13_db`.`SignosVitales`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospg13_db`.`SignosVitales` (
  `sig_id` INT NOT NULL,
  `sig_spo2` INT NOT NULL,
  `sig_resp` INT NOT NULL,
  `sig_ecg` INT NOT NULL,
  `sig_temp` INT NOT NULL,
  `sig_nibp` INT NOT NULL,
  `sig_glic` INT NOT NULL,
  `sig_historia` VARCHAR(90) NOT NULL,
  `sig_sugerencia` VARCHAR(90) NOT NULL,
  `sig_paciente` INT NOT NULL,
  PRIMARY KEY (`sig_id`, `sig_paciente`),
  INDEX `fk_SignosVitales_Paciente1_idx` (`sig_paciente` ASC) VISIBLE,
  CONSTRAINT `fk_SignosVitales_Paciente1`
    FOREIGN KEY (`sig_paciente`)
    REFERENCES `hospg13_db`.`Paciente` (`pac_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
