from .crearusuarioview import CrearUsuarioView
from .crearPsaludview import CrearPersonalSaludview
from .crearpacienteview import CrearPacienteView
from .crearfamiliarview import CrearFamiliarView
from .usuarioDetailView import UsuarioDetailView
from .pacientedetailview import PacienteDetailView
from .Psaluddetailview import PersonalSaludDetailView
from .familiardetailview import FamiliarDetailView